token:
  expiration_time: 864000000 
  secret: user_token_native_application_changed_#2

gateway:
  ip: 172.18.0.1

encrypt:
  keyStore:
    location: file://${user.home}/work/spring-cloud/configserver/server.jks
    password: 123456
    alias: mytestkey
    secret: 123456