spring:
  application:
    name: user-service
  datasource:
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pmh?characterEncoding=UTF-8&serverTimezone=UTC

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    show-sql: true
    open-in-view: false

sql:
  init:
    platform: mysql

mh:
  value: "{cipher}80c0523175dab0be8f255543577738acdd00b22bd93e473e74d329a9b18f7679"

server:
  port: 8089

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  #    prefer-ip-address: true
  #    ip-address: ${server.address}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    fetch-registry: true
    register-with-eureka: true


token:
  expiration_time: 86400000
  secret: mh1004mh1004mh1004mh1004mh1004mh1004mh1004mh1004mh1004mh1004mh1004mh1004mh1004mh1004mh1004mh1004mh1004mh1004mh1004mh1004mh1004mh1004

gateway:
  ip: 127.0.0.1

